CREATE DATABASE PETS;
GO

USE PETS;
GO

CREATE TABLE Clinicas(
	idClinica INT PRIMARY KEY IDENTITY(1,1),
	RazaoSocial VARCHAR(200) NOT NULL UNIQUE,
	CNPJ char(14) NOT NULL UNIQUE,
	Endereco VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE TABLE TiposPets(
	idTipoPet INT PRIMARY KEY IDENTITY(1,1),
	Descricao VARCHAR(200) UNIQUE
);
GO

CREATE TABLE Racas(
	idRaca INT PRIMARY KEY IDENTITY(1,1),
	idTipoPet INT FOREIGN KEY REFERENCES TiposPets (idTipoPet),
	Descricao VARCHAR(200) UNIQUE
);
GO

CREATE TABLE Donos(
	idDono INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE TABLE Pets(
	idPet INT PRIMARY KEY IDENTITY(1,1),
	idRaca INT FOREIGN KEY REFERENCES Racas (idRaca),
	idDono INT FOREIGN KEY REFERENCES Donos (idDono),
	Nome VARCHAR(200) NOT NULL UNIQUE,
	DataNascimento DATE
);
GO


CREATE TABLE Veterinarios(
	idVeterinarios INT PRIMARY KEY IDENTITY(1,1),
	idClinica INT FOREIGN KEY REFERENCES Clinicas (idClinica),
	Nome VARCHAR(200) NOT NULL UNIQUE,
	CRMV CHAR(6) UNIQUE
);
GO

CREATE TABLE Atendimentos(
	idAtendimento INT PRIMARY KEY IDENTITY(1,1),
	idVeterinario INT FOREIGN KEY REFERENCES Veterinarios (idVeterinarios),
	idPet INT FOREIGN KEY REFERENCES Pets (idPet),
	Descricao VARCHAR(200) UNIQUE,
	DataAtendimento DATE
);
GO